
[lint]
select = ["E", "F", "UP", "ICN001", "W292", "I001", "PYI"]
ignore = ["PYI034"]

[lint.isort]
known-first-party = ["tests", "scipy-stubs", "scripts"]
extra-standard-library = ["typing_extensions"]

[lint.flake8-import-conventions.aliases]
numpy = "np"

[lint.per-file-ignores]
# ignore undefined name reveal_type in test files
# ignore line-too-long as tests require annotations inline to work
"tests/reveal/*" = ["F821", "E501"]
# common typevars and typealiases in stubs
"src/scipy-stubs/sparse/typing.pyi" = ["PYI018", "PYI047"]
# allow star imports in init
"src/scipy-stubs/sparse/__init__.pyi" = ["F403", "F405"]
