name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.2.33/install.sh | sh
      - name: Set up Python 3.10
        run: uv python install python3.10
      - name: Install the project
        run: uv sync --dev --locked
      - name: Run tests
        run: uv run tox --quiet
